package io.clroot.hibernate.reactive.spring.boot.repository.query

import io.clroot.hibernate.reactive.spring.boot.repository.query.condition.ConditionBuilderRegistry
import org.springframework.data.domain.Sort
import org.springframework.data.repository.query.parser.Part
import org.springframework.data.repository.query.parser.PartTree

/**
 * Test-only parity oracle that preserves behavior before Issue #54.
 *
 * It is not used for production query generation. Change it only when intentionally changing
 * existing Spring-facing query behavior so regressions in the new neutral compiler are detected.
 */
internal class PartTreeHqlBuilder(
    private val entityName: String,
    private val partTree: PartTree,
) {

    companion object {
        private val SAFE_PROPERTY_PATH = Regex("[\\p{L}_$][\\p{L}\\p{N}_$]*(\\.[\\p{L}_$][\\p{L}\\p{N}_$]*)*")

        /** Placeholders generated by this builder, not user input, so replacement is safe. */
        private val PARAMETER_PLACEHOLDER = Regex(":p\\d+")
    }

    private var parameterIndex = 0
    private val parameterBinders = mutableListOf<ParameterBinder>()

    /** Builds the HQL query and parameter binders. */
    fun build(): HqlBuildResult {
        resetState()

        val hql = when {
            partTree.isCountProjection -> buildCountQuery()
            partTree.isExistsProjection -> buildExistsQuery()
            partTree.isDelete -> buildDeleteQuery()
            else -> buildSelectQuery()
        }

        return HqlBuildResult(hql, parameterBinders.toList())
    }

    /** Builds HQL using a dynamic sort when present, otherwise the method-name sort. */
    fun buildWithSort(dynamicSort: Sort?): HqlBuildResult {
        resetState()

        val hql = when {
            partTree.isCountProjection -> buildCountQuery()
            partTree.isExistsProjection -> buildExistsQuery()
            partTree.isDelete -> buildDeleteQuery()
            else -> buildSelectQueryWithSort(dynamicSort)
        }

        return HqlBuildResult(hql, parameterBinders.toList())
    }

    /** Builds COUNT HQL for page return types. */
    fun buildCountHql(): String {
        resetState()
        return buildCountQuery()
    }

    private fun resetState() {
        parameterIndex = 0
        parameterBinders.clear()
    }

    private fun buildSelectQuery(): String = buildSelectQueryWithSort(null)

    private fun buildSelectQueryWithSort(dynamicSort: Sort?): String {
        val where = buildWhereClause()
        val effectiveSort = dynamicSort?.takeIf { it.isSorted } ?: partTree.sort
        val orderBy = buildOrderByClause(effectiveSort)

        return buildString {
            if (partTree.isDistinct) append("SELECT DISTINCT e ")
            append("FROM $entityName e")
            if (where.isNotEmpty()) append(" WHERE $where")
            if (orderBy.isNotEmpty()) append(" ORDER BY $orderBy")
        }
    }

    private fun buildCountQuery(): String {
        val where = buildWhereClause()
        val countExpression = if (partTree.isDistinct) "COUNT(DISTINCT e)" else "COUNT(e)"
        return buildString {
            append("SELECT $countExpression FROM $entityName e")
            if (where.isNotEmpty()) append(" WHERE $where")
        }
    }

    private fun buildExistsQuery(): String {
        val where = buildWhereClause()
        return buildString {
            append("SELECT 1 FROM $entityName e")
            if (where.isNotEmpty()) append(" WHERE $where")
        }
    }

    /**
     * Builds the SELECT used by derived `deleteBy...` methods to find entities to remove.
     *
     * A bulk `DELETE` bypasses cascades and `@Version`, so entities are loaded and removed
     * individually to match Spring Data JPA.
     */
    private fun buildDeleteQuery(): String {
        val where = buildWhereClause()
        return buildString {
            append("FROM $entityName e")
            if (where.isNotEmpty()) append(" WHERE $where")
        }
    }

    private fun buildWhereClause(): String {
        val orParts = partTree.toList()
        if (orParts.isEmpty()) return ""

        return orParts.joinToString(" OR ") { orPart ->
            val andConditions = orPart.map { part -> buildCondition(part) }.toList()
            if (andConditions.size > 1) {
                "(${andConditions.joinToString(" AND ")})"
            } else {
                andConditions.joinToString(" AND ")
            }
        }
    }

    /** Converts a Part to an HQL predicate through [ConditionBuilderRegistry]. */
    private fun buildCondition(part: Part): String {
        val propertyPath = "e.${part.property.toDotPath()}"
        val ignoreCase = shouldIgnoreCase(part)
        val builder = ConditionBuilderRegistry.get(part.type)
        val property = if (ignoreCase) "LOWER($propertyPath)" else propertyPath
        val result = builder.build(property, parameterIndex)

        parameterBinders.addAll(result.binders)
        parameterIndex += result.paramCount

        // Parameterless predicates such as IS NULL have no case sensitivity to apply.
        if (!ignoreCase || result.paramCount == 0) return result.condition

        return result.condition.replace(PARAMETER_PLACEHOLDER) { "LOWER(${it.value})" }
    }

    /**
     * Determines whether to apply `IgnoreCase`.
     *
     * `IgnoreCase` (ALWAYS) fails at startup for non-String properties, while
     * `AllIgnoreCase` (WHEN_POSSIBLE) applies only to String properties.
     */
    private fun shouldIgnoreCase(part: Part): Boolean {
        val isStringProperty = part.property.leafProperty.type == String::class.java

        return when (part.shouldIgnoreCase()) {
            Part.IgnoreCaseType.ALWAYS -> {
                if (!isStringProperty) {
                    throw IllegalStateException(
                        "IgnoreCase cannot be applied to non-String property " +
                                "'${part.property.toDotPath()}' of type ${part.property.leafProperty.type.name}",
                    )
                }
                true
            }

            Part.IgnoreCaseType.WHEN_POSSIBLE -> isStringProperty
            else -> false
        }
    }

    private fun buildOrderByClause(sort: Sort): String {
        if (sort.isUnsorted) return ""
        return sort.map { order ->
            val direction = if (order.isAscending) "ASC" else "DESC"
            val property = order.property.also {
                require(SAFE_PROPERTY_PATH.matches(it) && "class" !in it.split('.')) {
                    "Invalid sort property"
                }
            }
            val expression = if (order.isIgnoreCase) "LOWER(e.$property)" else "e.$property"
            "$expression $direction"
        }.joinToString(", ")
    }
}

/**
 * HQL build result.
 */
internal data class HqlBuildResult(
    val hql: String,
    val parameterBinders: List<ParameterBinder>,
)
